- name: Add wst group
  group: name=wst state=present

- name: Add admins
  user: name={{ item.user }} groups="sudo,wst"
  with_items:
    - "{{ ssh_admins }}"

- name: Remove preinstalled users
  user: name={{ item.user }} state=absent remove=yes
  with_items:
    - "{{ absent_users }}"

- name: configure sudoers
  lineinfile: "dest=/etc/sudoers backup=yes state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD:ALL'"

- include: keys.yml
